name: Rancher Best Practice Documentation
description: Documentation for Rancher Best Practices


markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems:
  - jekyll-redirect-from

# Dockerfile will add baseurl and url
