name: Rancher Best Practice Documentation
description: Documentation for Rancher Best Practices


# Changing these will require updates to Dockerfile
URL: http://rancher.github.io/best-practice-guide
baseurl: ""

exclude: []

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems:
  - jekyll-redirect-from
